### ISSUE TITLE
Merge dev into master?

### ISSUE THREAD

**Issue by nathanwalker-sp** [asn32/weighted-nmf#1]
Hi! This is a useful package! I figured it might be good to merge dev into master, which solves the 'fit_transfrom' typo?

Cheers!
-Nathan

**Comment by asn32** [comment]
Hi Nathan, glad you found the package useful - I've just fixed the typos and uploaded an updated version to pypi. Let me know if you spot any other errors, or submit a PR.  

Thanks!
